version: 1.0.{build}
image: Visual Studio 2019
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: "{version}"
  package_version: "{version}"
before_build:
  - dotnet restore
build:
  verbosity: normal
after_build:
  - dotnet pack Pair -v=n /p:Configuration=Release /p:PackageVersion=%APPVEYOR_BUILD_VERSION%
artifacts:
- path: '**\*.nupkg'
  name: NuGet Packages
deploy:
  provider: NuGet
  api_key:
    secure: A2i62xzXSQpp4EML7xhXFE/r8xbkaycbJeJGjrINpkbnH/dQI7slbguOSN2b+QXD
  artifact: /.*\.nupkg/
  on:
    branch: 1.0